### ISSUE TITLE
ios上兼容性有问题

### ISSUE THREAD

**Issue by Neco86** [Xiumuzaidiao/Day-night-toggle-button#6]
<img width="194" alt="image" src="https://github.com/Xiumuzaidiao/Day-night-toggle-button/assets/33189641/21e712a8-c891-4ebe-a823-031ed328da17">

**Comment by Xiumuzaidiao** [comment]
I don't have an IOS device right now. You can use the initial code version to test it

**Comment by Xiumuzaidiao** [comment]
这个问题被解决啦
